<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('settings')->insert([
            'title' => 'Finovus settings',
            'site_name' => 'Finovus',
            'site_description' => 'A new way of doing fintech',
            'email' => 'admin@finovus.com',
            'support_email' => 'support@finous.com',
            'phone_number' => '1234567890',
            'balance_reg' => 0.00,
            'email_notification' => true,
            'sms_notification' => false,
            'email_notify' => true,
            'sms_notify' => false,
            'kyc' => false,
            'fixed_transfer_charge' => 0.00,
            'percent_transfer_charge' => 0.00,
            'minimum_transfer' => 0.00,
            'maximum_transfer' => 0.00,
            'fixed_merchant_charge' => 0.00,
            'percent_merchant_charge' => 0.00,
            'fixed_invoice_charge' => 0.00,
            'percent_invoice_charge' => 0.00,
            'fixed_product_charge' => 0.00,
            'percent_product_charge' => 0.00,
            'fixed_single_charge' => 0.00,
            'percent_single_charge' => 0.00,
            'fixed_donation_charge' => 0.00,
            'percent_donation_charge' => 0.00,
            'fixed_subscription_charge' => 0.00,
            'percent_subscription_charge' => 0.00,
            'fixed_membership_charge' => 0.00,
            'percent_membership_charge' => 0.00,
            'fixed_service_charge' => 0.00,
            'percent_service_charge' => 0.00,
            'fixed_withdrawal_charge' => 0.00,
            'percent_withdrawal_charge' => 0.00,
            'fixed_deposit_charge' => 0.00,
            'percent_deposit_charge' => 0.00,
            'fixed_payment_charge' => 0.00,
            'percent_payment_charge' => 0.00,
            'fixed_refund_charge' => 0.00,
            'percent_refund_charge' => 0.00,
            'fixed_recharge_charge' => 0.00,
            'percent_recharge_charge' => 0.00,
            'fixed_virtual_create_charge' => 0.00,
            'percent_virtual_create_charge' => 0.00,
            'fixed_virtual_charge' => 0.00,
            'percent_virtual_charge' => 0.00,
            'fixed_bill_charge' => 0.00,
            'percent_bill_charge' => 0.00,
            'registration' => false,
            'withdrawal_limit' => 0.00,
            'starter_limit' => 0.00,
            'withdrawal_duration' => 0,
            'merchant' => false,
            'transfer' => false,
            'request_money' => false,
            'invoice' => false,
            'store' => false,
            'subscription' => false,
            'bill' => false,
            'virtual_card' => false,
            'livechat' => false,
            'language' => 'en',
            'recaptcha' => false,
            'next_settlement' => now(),
            'duration' => 0,
            'extended_period' => 0,
            'period' => 0,
            'virtual_card_no' => false,
            'virtual_card_min' => 0.00,
            'virtual_card_max' => 0.00,
            'btc_wallet' => null,
            'btc_sell' => 0.00,
            'btc_buy' => 0.00,
            'eth_wallet' => null,
            'eth_buy' => 0.00,
            'eth_sell' => 0.00,
            'ethereum' => false,
            'bitcoin' => false,
            'solana' => false,
            'sol_wallet' => null,
            'sol_buy' => 0.00,
            'sol_sell' => 0.00,
            'min_btc_sell' => 0.00,
            'min_btc_buy' => 0.00,
            'min_eth_sell' => 0.00,
            'min_eth_buy' => 0.00,
            'min_sol_sell' => 0.00,
            'min_sol_buy' => 0.00,
            'btc_charge' => 0.00,
            'eth_charge' => 0.00,
            'sol_charge' => 0.00,
            'stripe_chargebacks' => 0.00,
            'welcome_message' => 'Welcome to our platform!',
            'stripe_connect' => false,
            'lock_code' => null,
            'kyc_restriction' => false,
            'country_restriction' => false,
            'debit_currency' => 'USD',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}